name: Kinetic

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ kinetic-devel ]
  pull_request:
    branches: [ kinetic-devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  kinetic-devel :
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - kinetic
        include:
            # Kinetic Kame (May 2016 - May 2021)
          - docker_image: ubuntu:xenial
            ros_distribution: kinetic
            ros_version: 1
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.2.1
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: turtlebot3_autorace_2020
          target-ros1-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
